name: Validate

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks-plugins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show PR base and head
        run: |
          echo "Base branch is: ${{ github.event.pull_request.base.ref }}"
          echo "Source branch is: ${{ github.event.pull_request.head.ref }}"

      - name: Diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-status origin/${{ github.event.pull_request.base.ref }}...HEAD

      - name: Validate
        # All the integrations in the repo should already be valid.
        # If this fails, that means this PR for an integration is invalid.
        run: |
          python3 ./workflow/validate.py "${{ github.event.pull_request.base.ref }}"
